version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: django_user        # Cambiado de root a django_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: ProyectoMainAPP.settings
    volumes:
      - .:/app

volumes:
  db_data: